### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [Xposed-Modules-Repo/org.matrix.chromext#11]
May I ask which license this app falls under? Source has indicators for Apache-2.0 but also "some BSD style license". Clarification would be much appreciated. Thanks in advance!

**Comment by JingMatrix** [comment]
This is just a mirror repo, you qustion is answered here: https://github.com/JingMatrix/ChromeXt/issues/18

**Comment by IzzySoft** [comment]
Ugh, that was unexpected (mirroring a repo on the very same server). And there I thought this looks strangely familiar – now I know why :see_no_evil: Thanks!
