### ISSUE TITLE
Please add support for Samsung internet 

### ISSUE THREAD

**Issue by ale82to** [Xposed-Modules-Repo/org.matrix.chromext#13]
Please consider adding support for Samsung internet ,thank you very much!

**Comment by JingMatrix** [comment]
Unfortunately, Samsung internet has changed too much of Chromium.
Though it is possible to reverse engineering this browser, it is too much work to do comparing to my interest on this browser.

**Comment by JingMatrix** [comment]
Samsung Internet is supported now, see [the original ChromeXt project](https://github.com/JingMatrix/ChromeXt).
You can test it now, or wait for the next release.
